import request from "graphql-request";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import { useState } from "react";
import BlogPost from "../components/BlogCard";
import Image from "next/image";
import Link from "next/link";

const instacms = new GraphQLClient(
  "https://ca-central-1.cdn.hygraph.com/content/clbk2a6mw2oes01tfcxgz9ish/master"
);

const QUERY = gql`
  {
    posts {
      id
      caption {
        text
      }
      picture {
        url
        height
        width
      }
      instagramUser {
        username
        profilePicture {
          url
          height
          width
        }
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await instacms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <Link href={"/posts/" + post.instagramUser.username}>
            <div className={styles.card}>
              <div className={styles.imgContainer}>
                {post.instagramUser.username}
                <Image src={post.picture.url} width="250" height="250" />
                <b>{post.caption.text}</b>
              </div>
            </div>
          </Link>
        ))}
      </main>
    </div>
  );
}
